const titles = [
  { "title": "Frontend Developer", "slug": "frontend-developer" },
  { "title": "Backend Developer", "slug": "backend-developer" },
  { "title": "Full Stack Developer", "slug": "full-stack-developer" },
  { "title": "Software Engineer", "slug": "software-engineer" },
  { "title": "Mobile App Developer", "slug": "mobile-app-developer" },
  { "title": "iOS Developer", "slug": "ios-developer" },
  { "title": "Android Developer", "slug": "android-developer" },
  { "title": "Web Developer", "slug": "web-developer" },
  { "title": "Data Scientist", "slug": "data-scientist" },
  { "title": "Data Analyst", "slug": "data-analyst" },
  { "title": "Machine Learning Engineer", "slug": "machine-learning-engineer" },
  { "title": "AI Engineer", "slug": "ai-engineer" },
  { "title": "DevOps Engineer", "slug": "devops-engineer" },
  { "title": "Site Reliability Engineer", "slug": "site-reliability-engineer" },
  { "title": "QA Engineer", "slug": "qa-engineer" },
  { "title": "Test Automation Engineer", "slug": "test-automation-engineer" },
  { "title": "Cloud Engineer", "slug": "cloud-engineer" },
  { "title": "Cloud Architect", "slug": "cloud-architect" },
  { "title": "Solutions Architect", "slug": "solutions-architect" },
  { "title": "Database Administrator", "slug": "database-administrator" },
  { "title": "Network Engineer", "slug": "network-engineer" },
  { "title": "Security Analyst", "slug": "security-analyst" },
  { "title": "Cybersecurity Engineer", "slug": "cybersecurity-engineer" },
  { "title": "Penetration Tester", "slug": "penetration-tester" },
  { "title": "Product Manager", "slug": "product-manager" },
  { "title": "Project Manager", "slug": "project-manager" },
  { "title": "Scrum Master", "slug": "scrum-master" },
  { "title": "Business Analyst", "slug": "business-analyst" },
  { "title": "UI/UX Designer", "slug": "uiux-designer" },
  { "title": "Visual Designer", "slug": "visual-designer" },
  { "title": "Graphic Designer", "slug": "graphic-designer" },
  { "title": "Interaction Designer", "slug": "interaction-designer" },
  { "title": "Game Developer", "slug": "game-developer" },
  { "title": "Game Designer", "slug": "game-designer" },
  { "title": "AR/VR Developer", "slug": "arvr-developer" },
  { "title": "Blockchain Developer", "slug": "blockchain-developer" },
  { "title": "Smart Contract Developer", "slug": "smart-contract-developer" },
  { "title": "Technical Writer", "slug": "technical-writer" },
  { "title": "IT Support Specialist", "slug": "it-support-specialist" },
  { "title": "Helpdesk Technician", "slug": "helpdesk-technician" },
  { "title": "System Administrator", "slug": "system-administrator" },
  { "title": "Network Administrator", "slug": "network-administrator" },
  { "title": "Embedded Systems Engineer", "slug": "embedded-systems-engineer" },
  { "title": "Hardware Engineer", "slug": "hardware-engineer" },
  { "title": "Electronics Engineer", "slug": "electronics-engineer" },
  { "title": "Computer Vision Engineer", "slug": "computer-vision-engineer" },
  { "title": "NLP Engineer", "slug": "nlp-engineer" },
  { "title": "Robotics Engineer", "slug": "robotics-engineer" },
  { "title": "Research Scientist", "slug": "research-scientist" },
  { "title": "Statistician", "slug": "statistician" },
  { "title": "Big Data Engineer", "slug": "big-data-engineer" },
  { "title": "ETL Developer", "slug": "etl-developer" },
  { "title": "BI Developer", "slug": "bi-developer" },
  { "title": "CRM Developer", "slug": "crm-developer" },
  { "title": "ERP Consultant", "slug": "erp-consultant" },
  { "title": "Salesforce Developer", "slug": "salesforce-developer" },
  { "title": "Marketing Analyst", "slug": "marketing-analyst" },
  { "title": "SEO Specialist", "slug": "seo-specialist" },
  { "title": "Content Strategist", "slug": "content-strategist" },
  { "title": "Digital Marketer", "slug": "digital-marketer" },
  { "title": "Social Media Manager", "slug": "social-media-manager" },
  { "title": "Growth Hacker", "slug": "growth-hacker" },
  { "title": "Performance Marketer", "slug": "performance-marketer" },
  { "title": "Affiliate Manager", "slug": "affiliate-manager" },
  { "title": "Customer Success Manager", "slug": "customer-success-manager" },
  { "title": "Technical Recruiter", "slug": "technical-recruiter" },
  { "title": "HR Manager", "slug": "hr-manager" },
  { "title": "Talent Acquisition Specialist", "slug": "talent-acquisition-specialist" },
  { "title": "Instructional Designer", "slug": "instructional-designer" },
  { "title": "Learning & Development Manager", "slug": "learning-development-manager" },
  { "title": "Education Technologist", "slug": "education-technologist" },
  { "title": "Academic Researcher", "slug": "academic-researcher" },
  { "title": "DevRel Engineer", "slug": "devrel-engineer" },
  { "title": "Open Source Contributor", "slug": "open-source-contributor" },
  { "title": "Software Architect", "slug": "software-architect" },
  { "title": "Application Developer", "slug": "application-developer" },
  { "title": "Firmware Engineer", "slug": "firmware-engineer" },
  { "title": "Computer Engineer", "slug": "computer-engineer" },
  { "title": "IT Consultant", "slug": "it-consultant" },
  { "title": "Software Consultant", "slug": "software-consultant" },
  { "title": "Platform Engineer", "slug": "platform-engineer" },
  { "title": "Middleware Engineer", "slug": "middleware-engineer" },
  { "title": "Release Manager", "slug": "release-manager" },
  { "title": "Configuration Manager", "slug": "configuration-manager" },
  { "title": "Version Control Specialist", "slug": "version-control-specialist" },
  { "title": "Build Engineer", "slug": "build-engineer" },
  { "title": "API Developer", "slug": "api-developer" },
  { "title": "Integration Engineer", "slug": "integration-engineer" },
  { "title": "Mobile UI Designer", "slug": "mobile-ui-designer" },
  { "title": "Voice UI Designer", "slug": "voice-ui-designer" },
  { "title": "Accessibility Specialist", "slug": "accessibility-specialist" },
  { "title": "Security Consultant", "slug": "security-consultant" },
  { "title": "Forensic Analyst", "slug": "forensic-analyst" },
  { "title": "IT Auditor", "slug": "it-auditor" },
  { "title": "Cloud Security Engineer", "slug": "cloud-security-engineer" },
  { "title": "Governance Risk Compliance Specialist", "slug": "governance-risk-compliance-specialist" },
  { "title": "Fintech Developer", "slug": "fintech-developer" },
  { "title": "Quant Developer", "slug": "quant-developer" },
  { "title": "Banking Software Developer", "slug": "banking-software-developer" },
  { "title": "Healthcare IT Specialist", "slug": "healthcare-it-specialist" },
  { "title": "Bioinformatics Scientist", "slug": "bioinformatics-scientist" },
  { "title": "Computational Biologist", "slug": "computational-biologist" },
  { "title": "E-commerce Manager", "slug": "e-commerce-manager" },
  { "title": "Logistics Tech Specialist", "slug": "logistics-tech-specialist" }
];

export default titles;
